export const clinics = [
  {
    id: 1,
    img: "https://cms.sehatq.com/cdn-cgi/image/f=auto/public/img/hospital_thumb/kalideres-jakarta-barat-HCFP00000015.jpg",
    nama: "Puskesmas Kecamatan Kalideres",
    address: "Jl. Tj. Pura No.30, RW.5, Pegadungan, Kec. Kalideres, Kota Jakarta Barat,",
    service_time: "08.00 - 16.00 WIB",
    city: "Jakarta Barat",
    contact: "0877-2224-4894",
    province: "Jakarta",
    postalcode: "11830",
  },
  {
    id: 2,
    img: "https://databank-kpap.jakarta.go.id/uploads/organisasi/PKM_Cengkareng.jpg",
    nama: "Puskesmas Kecamatan Cengkareng",
    address: "Jl. Kamal Raya No.2 RT.09/RW. 07, Cengkareng Barat",
    service_time: "08.00 - 16.00 WIB",
    city: "Jakarta Barat",
    contact: "021 - 29038167",
    province: "Jakarta",
    postalcode: "11730",
  },
  {
    id: 3,
    img: "https://m.angsamerah.com/wp-content/uploads/2017/02/angsamerah-clinic_01.jpg",
    nama: "Klinik Angsa Merah",
    address: "Jl. Johar No.6A, RW.6, Kb. Sirih, Kec. Menteng, Kota Jakarta Pusat,",
    service_time: "08.00 - 16.00 WIB",
    city: "Jakarta Pusat",
    contact: "021 - 3160251",
    province: "Jakarta",
    postalcode: "10340",
  },
  {
    id: 4,
    img: "https://databank-kpap.jakarta.go.id/uploads/organisasi/PKM_Cengkareng.jpg",
    nama: "Puskesmas Kecamatan Cengkareng",
    address: "Jl. Kamal Raya No.2 RT.09/RW. 07, Cengkareng Barat",
    service_time: "08.00 - 16.00 WIB",
    city: "Jakarta Barat",
    contact: "021 - 29038167",
    province: "Jakarta",
    postalcode: "11730",
  },
  {
    id: 5,
    img: "https://pkbidkijakarta.org/wp-content/uploads/2016/03/3-2.jpg",
    nama: "Klinik ProCare PKBI",
    address: "Jl. Pisangan Baru Selatan, RT.7/RW.9, Pisangan Baru, Kec. Matraman,",
    service_time: "08.00 - 16.00 WIB",
    city: "Jakarta Timur",
    contact: "0877-2224-4894",
    province: "Jakarta",
    postalcode: "13110",
  },
  {
    id: 6,
    img: "https://pkbidkijakarta.org/wp-content/uploads/2016/03/3-2.jpg",
    nama: "Klinik ProCare PKBI",
    address: "Jl. Pisangan Baru Selatan, RT.7/RW.9, Pisangan Baru, Kec. Matraman,",
    service_time: "08.00 - 16.00 WIB",
    city: "Jakarta Timur",
    contact: "0877-2224-4894",
    province: "Jakarta",
    postalcode: "13110",
  },
];
